### ISSUE TITLE
Support for custom piped instances

### ISSUE THREAD

**Issue by anxiouslelimo** [anandnet/Harmony-Music#103]
**Is your feature request related to a problem or new idea? Please describe.**
Custom piped instance implementation is helpful 1. obviously to add/remove custom instance 2. beneficial if for some reason auth instances list is not showing up like happening today. (https://github.com/TeamPiped/Piped/issues/3240)

**Describe the solution you'd like**
Ability to add custom instance like in libretube

**Additional context**
If i am self hosting piped current implementation doesnt let me link the instance.

**Comment by anandnet** [comment]
Hi @anxiouslelimo  Already implemented in current  version. Need to wait some time until instance list api return an error response(i don't know why this is taking too much time, you need to wait at least 1min).
- Open link popup 
- wait until error message appear as below screenshot
- now you will be able to select custom instance 
<img src ="https://github.com/anandnet/Harmony-Music/assets/45705030/be48cedc-d727-4469-ac40-10d9a1f3117f" height=200>
<img src ="https://github.com/anandnet/Harmony-Music/assets/45705030/9d83e71c-ffea-4af7-a2ed-e303d320fc21" height=200>

**Comment by anandnet** [comment]
I have made some mistake in code that's why It's showing "some error occured!".  fixed now, probably this weekend i'll release new version.

**Comment by anandnet** [comment]
Fixed in V1.7.0.
