### ISSUE TITLE
It doesn't play the album offline

### ISSUE THREAD

**Issue by Azzman1984** [anandnet/Harmony-Music#113]
Hello there, downloading albums is fine but the problem is when I bookmark the album so I could listen for offline use then it doesn't play at all

Here's screenshots of the album I downloaded for offline use but it has the WiFi on and it plays absolutely fine
![Screenshot_20231226_234047](https://github.com/anandnet/Harmony-Music/assets/150800081/641181fd-395f-4b60-9e81-69652c5ff2af)

![Screenshot_20231226_234056](https://github.com/anandnet/Harmony-Music/assets/150800081/e5a850a9-de94-4bed-9587-263f7fc58120)

![Screenshot_20231226_234117](https://github.com/anandnet/Harmony-Music/assets/150800081/3001ec6d-19df-45e5-8298-0361381a9799)

Now here's screenshots of the same thing but with the WiFi off and it was suppose to play for offline use but it doesn't at all

![Screenshot_20231226_234653](https://github.com/anandnet/Harmony-Music/assets/150800081/77c5e928-d719-41d6-ba97-4f1d06da82be)

![Screenshot_20231226_234701](https://github.com/anandnet/Harmony-Music/assets/150800081/aecc0ce8-cdd9-4d34-a997-be009713bf83)

![Screenshot_20231226_234727](https://github.com/anandnet/Harmony-Music/assets/150800081/ae753461-a8da-48ae-a597-dc621d8cf168)

Could I suggest on this screenshot below to add an offline albums feature on the library playlist section so myself and many others could just on offline downloaded albums and play the albums in full and in proper tracklisting order without the need of WiFi

![Screenshot_20231226_234755](https://github.com/anandnet/Harmony-Music/assets/150800081/1d330a7d-aae8-408f-88ee-ed1981881cf8)

**Comment by anandnet** [comment]
i'll look into it

**Comment by seasidesongs** [comment]
Hi great app. Is it possible to try and sort the issue above re not being able to to play downloaded albums when off line
Is it also possible to make a donation for your endeavours so far
Regards Gary

**Comment by seasidesongs** [comment]
Hi
I still cannot play an album that i have saved off line. I can only play the songs though the downloaded songs section

**Comment by anandnet** [comment]
Hi @Azzman1984 and @seasidesongs check v1.8.0, Now bookmarked album/playlists can be accessed while offline.
