### ISSUE TITLE
Synced lyrics with new style

### ISSUE THREAD

**Issue by mohandan1** [anandnet/Harmony-Music#116]
The app have very beautiful and smooth UI.but lyrics should be synced and if there is one titled option for lyrics like yt music and Spotify instead of opening on album cover then it would be more beautiful.

**Comment by adityainduraj** [comment]
I actually prefer the album-cover implementation. This app is a fork of ViMusic, and I really like the UI of ViMusic.

**Comment by mohandan1** [comment]
Okey,but you can add as an option for 'SHOW IN FULL SCREEN'
And also as I seen lyrics are not synced....

**Comment by anandnet** [comment]
Synced lyrics available in v1.8.0, Full screen lyrics might be added in future release. Closing this for now.
