### ISSUE TITLE
Where is the download folder and format option?

### ISSUE THREAD

**Issue by ZeroOVi** [anandnet/Harmony-Music#119]
In the latest version 1.7.0 I can't find the download folder and download format options
![Screenshot_20231229-104104](https://github.com/anandnet/Harmony-Music/assets/109626815/df02fc64-c8fd-4366-95ab-417eed5a3ccf)

**Comment by anandnet** [comment]
Due to path mismatching issue in download database i have made app data dir default downloading location instead of external storage and hide those options. You can still access those options in settings just give a long press on streaming quality tile.
