### ISSUE TITLE
Ability to restore library database from ViMusic

### ISSUE THREAD

**Issue by astarq** [anandnet/Harmony-Music#12]
**Is your feature request related to a problem or new idea? Please describe.**
There is currently no option to restore/import playlists from other music streaming services or YT Music clients.

**Describe the solution you'd like**
It would be great if you could add the import/export feature from ViMusic. Hopefully this will be relatively simple to do!

**Describe alternatives you've considered**
An option to restore from YouTube playlists or Innertune would also be useful, but ViMusic makes more sense as it's users are the most likely to be attracted to Harmony.

**Additional context**
ViMusic exports are contained in a .db file.
ViMusic database backup/restore settings:
![Screenshot_20230706-124052_ViMusic](https://github.com/anandnet/Harmony-Music/assets/63871973/146ab4a7-a5b9-4501-8fd8-6240af2b36b0)

**Comment by anandnet** [comment]
@astarq  Import feature via sharing added in V1.3.0, Which was requested in #10.
You are now able to import Ytube/Ytubue Music Songs, Album, Playlist, Artist check <a href="https://github.com/anandnet/Harmony-Music/wiki/FAQ"> wiki=>FAQ </a>

Thanks for the idea, It's just a learning project 😊.

**Comment by astarq** [comment]
That's fantastic, thank you.

Even so, it's looking good so far ;)

**Comment by Nishanth-23** [comment]
We need to share a playlist

**Comment by anandnet** [comment]
@Nishanth-23  Local library playlists can't be shared because those are not stored in cloud.
You can share all the yt hosted playlists which are publicly available.
To share - open any playlist & click share icon.
<img src = "https://github.com/anandnet/Harmony-Music/assets/45705030/63762e14-cd8c-481d-80d7-7f39db8f0dd8" height=300>
