### ISSUE TITLE
App flagged as `Trojan`

### ISSUE THREAD

**Issue by vedxp** [anandnet/Harmony-Music#122]
**Describe the bug**
Harmony Music is flagged as `Trojan` on VirusTotal.

**Additional context**
[View the scan result](https://www.virustotal.com/gui/file/d2c123313fa15e09a21f5836812962687bf70a05275cc47894cf1431a8dea06d/detection)

**Comment by anandnet** [comment]
1/65 seems false positive. However will look into it. If anyone has any idea which behaviour causing flagged as trojen pls help me.

**Comment by vedxp** [comment]
> 1/65 seems false positive. However will look into it. If anyone has any idea which behaviour causing flagged as trojen pls help me.

This might help you: https://github.com/miru-project/miru-app/issues/150#issuecomment-1858305405

**Comment by anandnet** [comment]
By Removing AudioTags package this has been fixed ,<a href= "https://www.virustotal.com/gui/file/d9a957a6dc66660b367e0e61a7db20eab5a106259f35a1377e29b7970909f356?nocache=1">new report</a>

**Comment by anandnet** [comment]
Fixed in v1.8.0

**Comment by NguyenTrongThinh** [comment]
I look at the scan result again. It was updated 9 days ago: 0/65.
https://www.virustotal.com/gui/file/d2c123313fa15e09a21f5836812962687bf70a05275cc47894cf1431a8dea06d/detection

I think the anti-virus software is not identifying the virus correctly. Please review and bring this feature back.

**Comment by anandnet** [comment]
Will revert in next release.
