### ISSUE TITLE
Some downloaded songs won't play and sort of breaks the app.

### ISSUE THREAD

**Issue by Doodleguy** [anandnet/Harmony-Music#129]
Downloading certain songs seems to make all of the other downloaded songs unplayable until you delete it from downloads and restart the app. (lot more context at the end)

1. Download any songs / albums 
2. Download a song from Vanguard Sound.
3. The newly downloaded song time will go to 0:00 and every other already downloaded song will most likely showcase the same behavior.

**Expected behavior**
It should just play the songs since they already downloaded.

Screenshot of how it looks when it won't play and that's how any other song timestamp will appear too.
![TeddySong](https://github.com/anandnet/Harmony-Music/assets/32069243/8e7c99bb-98b7-4dc2-a15d-f492b451bb9d)

I'm using a Xiaomi Redmi Note 9 Pro | Android 12 / MIUI 14.

**Additional context**
I just recently downloaded the app and i went straight into downloading songs that i like as anyone could do, until i decided to download some PGR songs from Vanguard Sound and that's when everythin went downhill, someone with knowledge please at least help me understand why this is happening or help me fix it, i assume this could possibly happen with some other channels/artists but i've only seen it happen with his one so far.
I kept it a short and sweet as possible if any other info is needed feel free to ask.

**Comment by anandnet** [comment]
@Doodleguy thanks for reporting this issue. I have checked seems this is happening due to some special char used like in song name. Please avoid downloading songs with special char for now. I will try to fix this.

**Comment by anandnet** [comment]
Fixed in v1.8.0
