### ISSUE TITLE
The downloaded songs r not in the correct order

### ISSUE THREAD

**Issue by Azzman1984** [anandnet/Harmony-Music#132]
Hello there I downloaded an album and booked marked but when i clicked on it the album.. the tracklisting is not in the right order

Here's the screenshot of the album in the correct tracklisting
![Screenshot_20240111_150936](https://github.com/anandnet/Harmony-Music/assets/150800081/1af6f7e2-9722-4ff7-b630-8c4ed09b9ea9)
 
Then here's the screenshots of that same album but downloaded and book marked but the tracklisting in the wrong order

![Screenshot_20240111_150946](https://github.com/anandnet/Harmony-Music/assets/150800081/60d9634f-6cf4-4b28-9578-a40ec1809ea2)

![Screenshot_20240111_150956](https://github.com/anandnet/Harmony-Music/assets/150800081/e2a1910a-0c7e-4783-bdfc-3ee738bf3a19)

If u can fix this issue so I could play the album in the correct order offline then I would be very grateful.. thank u

**Comment by DeadSecTr** [comment]
Yup...can confirm that too

**Comment by anandnet** [comment]
Sorry guys, i havn't paid more attention on song order. i had just saved the playlist/album data in local db. Will be fixed in next release.

**Comment by DeadSecTr** [comment]
Please fix this bug cuz it is really annoying :(

**Comment by anandnet** [comment]
Fixed in v1.3.0
