### ISSUE TITLE
Implement loading icon

### ISSUE THREAD

**Issue by max5354** [anandnet/Harmony-Music#134]
It will be great if you implement loading icon. As for now there is no loading icon for reference you can see in screenshot there is no loading icon so we can't see music is really loading or not. Also i suggest you to implement loading icon in  edges of "play/pause" button that looks cool instead of implementing on thumbnail. I hope you understand. And extremely thanks for implementing my feature request/suggestion in new version and fixing bug.

![Screenshot_20240111-221221](https://github.com/anandnet/Harmony-Music/assets/90886938/ec6d9eb7-135d-40b7-815a-b06902ee3006)

**Comment by anandnet** [comment]
Added in v1.9.0
