### ISSUE TITLE
Harmony-Music Desktop Version

### ISSUE THREAD

**Issue by encryptiongs** [anandnet/Harmony-Music#136]
**Is your feature request related to a problem or new idea? Please describe.**
It isn't really a new idea, but since Harmony is developed with flutter, it should be possible to make a Desktop (Windows, Linux) Version of the app with just a few adjustments. It would be super cool since we could use our favourite music streaming app on PC too. 

**Describe the solution you'd like**
A Windows and Linux build in addition to the apk version. The design should work on desktop like on android (I guess?) 

**Describe alternatives you've considered**
A web version... But I think that is more difficult.

**Comment by anandnet** [comment]
Hello @encryptiongs thanks for the idea. Earlier i had worked on windows desktop app but unfortunaltly just_audio_windows plugin doesn't work properly so i had to drop this idea. For linux i haven't tried yet, i'll check for linux.

**Comment by encryptiongs** [comment]
Ok, that seems like a problem. Maybe another plug-in would work? I think there is an alternative way on windows... Maybe one day you can try it again if you have too much free time :)

**Comment by senolfndk** [comment]
can you add volume button for windows?

**Comment by senolfndk** [comment]
Can you add volume control button for windows version?
