### ISSUE TITLE
HM as "Browser"?

### ISSUE THREAD

**Issue by DeadSecTr** [anandnet/Harmony-Music#142]
Why shows in app info that could Harmony music set as a Browser?

**Comment by DeadSecTr** [comment]
![Screenshot_20240116-112431.png](https://github.com/anandnet/Harmony-Music/assets/90558189/ff1d7d46-25c4-4e6c-af7c-2d302661ff95)

**Comment by anandnet** [comment]
Fixed now in v1.9.0
