### ISSUE TITLE
Delete downloaded songs

### ISSUE THREAD

**Issue by DeadSecTr** [anandnet/Harmony-Music#143]
There is no posibility to delete downloaded songs,only download but no delete

**Comment by anandnet** [comment]
@DeadSecTr  If you remove any Song from "Library Songs" or "Downloads", downloaded file will be deleted as well.

**Comment by DeadSecTr** [comment]
Yes, but it would be much easier and better if there was a song delete function in the menu that appears when you hold the song and the pop-up menu appears.
