### ISSUE TITLE
No option to add a translation for the function.

### ISSUE THREAD

**Issue by MattSolo451** [anandnet/Harmony-Music#147]
On Hosted Weblate I did not find the option to add a translation for this feature (screenshot below). 
![Screenshot_20240119-175501_1](https://github.com/anandnet/Harmony-Music/assets/70535762/5741aada-255a-4890-9a8b-ec9ffaf8aaec)

Would it be possible to add it?

**Comment by anandnet** [comment]
Sorry i forgot that added now.
