### ISSUE TITLE
[Translation] Requesting owner to not add MTs

### ISSUE THREAD

**Issue by Kjev666** [anandnet/Harmony-Music#149]
@anandnet I observed that you were adding machine translated strings to a language I had partially translated - Esperanto. I noticed this because there were errors in the translated strings. Due to some work I had to put the translation on hold for a while but I can continue it now.

I request you to not add translations yourself if you don't know the language. It becomes more burdensome as I will need to check through the strings to see if there are any errors and that makes the work more difficult.

I made this issue here as I was unable to find any alternative ways to contact you.

**Comment by anandnet** [comment]
Thanks @Kjev666 for highlighting this. I will not add any MT strings further. Btw thanks again for your contribution 😊 .

**Comment by anandnet** [comment]
Also i have added "needs editing" flag in strings for which i had added translation. So, no need to look all strings you can directly review those from "Strings marked for edit" label.

**Comment by Kjev666** [comment]
> Also i have added "needs editing" flag in strings for which i had added translation. So, no need to look all strings you can directly review those from "Strings marked for edit" label.
> 

That's great! Thanks.
