### ISSUE TITLE
'Trending' section doesn't load!

### ISSUE THREAD

**Issue by MrDevil143** [anandnet/Harmony-Music#151]
**Describe the bug**

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Set discover content'
3. Click on 'Trending'
4. Restart the 'Harmony Music'
5. See error

**Expected behavior**
Exceptation: The Trending music or content will appear
Reality : It doesn't  load the 'Homepage"

**Screenshots**
![Screenshot_20240204_124301](https://github.com/anandnet/Harmony-Music/assets/158800356/71e68030-9267-43e3-aced-9f96717c9053)

**Smartphone (please complete the following information):**
 - Device: Vivo 1603 (Y55L)
 - OS: Android 6.1

**Additional context**
And it is showing 'Quick Picks' instead of showing showing 'Based on last intersections'

**Comment by anandnet** [comment]
seems ytmusic has removed tranding section from charts, will look into it. 
you need to play alteast one song after changing discover content to "Based on last interaction" to view change.

**Comment by anandnet** [comment]
its back, you may check now
