### ISSUE TITLE
Overwrite Downloaded song with same name

### ISSUE THREAD

**Issue by encryptiongs** [anandnet/Harmony-Music#152]
**Describe the bug**
If you download a song  und then another one with the same name the first one gets overwritten and if you play the first one offline then the second one is played. 

**To Reproduce**
1. Download for example "Behind Blue eyes" from Limp Bizkid and "Behind blue eyes" from ViZe
2. Play the first one offline
3. The ViZe version is played

**Expected behavior**
The correct song should be played. 

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 10 (umi) 
 - OS: Android 13, MIUI 14

**Additional context**
I think the songs should be saved in a file like "<songName><idOrPrimaryKey>.opus" to prevent naming conflicts.

**Comment by anandnet** [comment]
@encryptiongs thanks for reporting, Yes this is happening due to same file name. I will include artist name/song id in the filename, that will probably resolve this issue.

**Comment by anandnet** [comment]
Fixed now in v1.9.0.
