### ISSUE TITLE
Play previous/next song on swiping mini player

### ISSUE THREAD

**Issue by max5354** [anandnet/Harmony-Music#161]
It will be great if you implement feature that play previous/next on swiping left/right on mini player. As for now if we swipe left/right than nothing happenes. But if you implement that feature than we can change songs by swiping left/right on mini player.

![20240214_172958](https://github.com/anandnet/Harmony-Music/assets/90886938/4072f429-750a-413e-b9ec-abc99b7ab754)

**Comment by anandnet** [comment]
Available now in new version
