### ISSUE TITLE
Song not downloadable or removable from  local playlist

### ISSUE THREAD

**Issue by encrystudio** [anandnet/Harmony-Music#162]
**Describe the bug**
Some random songs cannot be downloaded or removed from a playlist. 

**To Reproduce**
1. Go to a playlist 
2. Press a song with that issue, for example "Freedom" by Ranji and Ghost Rider
3. Try or download it (will be stuck on 0%)
4. Try to remove from playlist (won't be deleted from playlist)

**Screenshots**
![Screenshot_2024-02-15-01-48-45-708_com.anandnet.harmonymusic.jpg](https://github.com/anandnet/Harmony-Music/assets/94799008/43d9aeb1-853d-4053-ac60-899d28b2a0c2)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 10 (umi)
 - OS: MIUI 14 based on Android 13

**Additional context**
The Song was originally added to the playlist by selecting all songs from "Favorites" and add to playlist.

**Comment by anandnet** [comment]
Please try in new app session.

**Comment by anandnet** [comment]
I can reproduce this issue now, will fix and release a new version soon
