### ISSUE TITLE
Add metadata (Music tag) to music files exported to another folder.

### ISSUE THREAD

**Issue by NguyenTrongThinh** [anandnet/Harmony-Music#163]
**Please export the downloaded file to another folder with the file's metadata.**
I'm very happy because the application now allows exporting downloaded files to another folder. This could allow me to play music on the DAC system instead of just listening to it on my phone. Currently, the output file has lost metadata, so the music player software cannot classify songs by artist or album. I recommend adding metadata to output files so music players can recognize and categorize songs. Here's a list of common music metadata:

- Title: The name of the song.
- Artist: The individual or group who performed the song.
- Album: The collection or album the song belongs to.
- Genre: The musical category or style of the song.
- Release Year: The year when the song was released.
- Duration: The length of the song in minutes and seconds.
- Track Number: The position of the song on the album.
- Composer: The person who composed the music.
- Lyricist: The person who wrote the lyrics.
- Label: The record label that released the song.
- ISRC (International Standard Recording Code): A unique identifier for the recording.
- BPM (Beats Per Minute): The tempo or speed of the song.
- Key: The musical key of the song.
- File Format: The format of the audio file (e.g., MP3, WAV, FLAC).
- Bitrate: The amount of data processed per unit of time in the audio file.
- Sample Rate: The number of samples of audio carried per second in the file.
- File Size: The size of the audio file in kilobytes or megabytes.
- Album Art: The visual representation associated with the album or song.

**Alternative solution**
If this method is difficult, I suggest allowing exporting files by Album in the bookmark album section, or by playlist in the bookmark playlist section to a folder created by the user (Harmonic music asks where to save the music), but I think that Adding metadata and files will make the software more perfect.

**Comment by anandnet** [comment]
I have added earlier but due to used Audiotags package, VirusTotal vendor was showing this app as Trojen. So i have removed. check #122

**Comment by NguyenTrongThinh** [comment]
Did you mean this package: https://pub.dev/packages/audiotags? Which version that you used?

**Comment by anandnet** [comment]
Reverted in new version, only available for m4a format. Make sure m4a selected in settings before downloading any song.
