### ISSUE TITLE
Queue

### ISSUE THREAD

**Issue by Kabuki1212** [anandnet/Harmony-Music#165]
I Cant Move Songs On The Queue

**Comment by Kabuki1212** [comment]
![Screenshot_20240220-154244](https://github.com/anandnet/Harmony-Music/assets/160406069/9a8e670a-2215-4c2a-a6f0-cc683a191cb3)
 
Still Not Working 😭

**Comment by anandnet** [comment]
I have made changes in code only. Fixes will be appear in next relaease.

**Comment by anandnet** [comment]
Fixed now.
