### ISSUE TITLE
Music recommendation

### ISSUE THREAD

**Issue by siggi1984** [anandnet/Harmony-Music#166]
Spotify displays music recommendations at the end of a playlist, which you can then add to a playlist or play next, for example.

I know that YouTube also offers this based on the currently playing song.

This implementation would be cool for discovering new music that suits your tastes.

I think this developer has implemented it well. See screenshot.
https://github.com/25huizengek1/ViMusic

![302751955-21bfd78c-f5a4-4505-a102-f74d583affa4](https://github.com/anandnet/Harmony-Music/assets/103368536/a623f401-edbd-4fe7-980d-86f271a8ad91)

**Comment by rishi-wqd190004** [comment]
I am planning to work on this. Any upward suggestions? @Atalanttore
