### ISSUE TITLE
A volume slider on the windows client.

### ISSUE THREAD

**Issue by Doodleguy** [anandnet/Harmony-Music#169]
**Is your feature request related to a problem or new idea? please describe**

I think this counts as a feature but i decided to give the Windows client a try and i realized something very quickly or i might just be blind but there doesn't seem to be a volume slider or some way to control the volume at least within' the app.

**Describe the solution you'd like**
A volume slider, nothing too crazy it just need to stop certain songs from destroying my ears in an easy and fast way, lol.

**Describe alternatives you've considered**
Slider.. or make the icon a small wheel?

**Additional context**
Please, i'm losing my hearing right now, i'm just joking, you already know what i mean, i won't be using the pc client for now for now but i'm sure you'll figure it out or tell me if i'm blind.

**Comment by anandnet** [comment]
Added in new version.
