### ISSUE TITLE
Not everything is displayed on the artist pag

### ISSUE THREAD

**Issue by siggi1984** [anandnet/Harmony-Music#17]
With some artists not everything is shown: e.g.: no albums are shown although the artist has some, the same with singles or songs.

See screenshot
![Screenshot_20230713-112839](https://github.com/anandnet/Harmony-Music/assets/103368536/5ec71f37-1184-4a0d-8656-05f6a17d826d)
![Screenshot_20230713-112843](https://github.com/anandnet/Harmony-Music/assets/103368536/b1f4fc18-f013-472f-b2b7-167332c7557c)
![Screenshot_20230713-112847](https://github.com/anandnet/Harmony-Music/assets/103368536/b8a667b8-08bc-4508-b593-cd13ad0e8a28)
![Screenshot_20230713-112910](https://github.com/anandnet/Harmony-Music/assets/103368536/ce1658a9-3843-4d00-9881-be9899c45e38)
![Screenshot_20230713-112915](https://github.com/anandnet/Harmony-Music/assets/103368536/d793cad4-729c-45ae-b490-33a1b1ee1c65)

**Comment by DickinsonSa** [comment]
Here here! I'd willingly donate (fix the donate link please) to get this working - an artist = albums, singles, playlists, overview.

You're looking at a killer app here **but** there's bits missing - it's not linking all the pieces properly.

**Comment by anandnet** [comment]
@siggi1984 & @DickinsonSa  Closing as this issue has been fixed in v1.3.1.

**Comment by siggi1984** [comment]
Thanks bro.

**Comment by DickinsonSa** [comment]
Great work, it's looking good - thanks.
