### ISSUE TITLE
Music randomly paused on mobile data

### ISSUE THREAD

**Issue by IAMGeeCee** [anandnet/Harmony-Music#170]
**Describe the bug**
I've found that when I listen on 4/5G the song will randomly stop (I'm assuming this its buffering)

**To Reproduce**
Go outside.
Open the app.
Play music that's not cached.

**Expected behavior**
After about 30 seconds it will stop for about 10 seconds 

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: Android 14

**Additional context**
N/A

**Comment by anandnet** [comment]
Buffering loading indicator added in new version
