### ISSUE TITLE
Transparent bottom

### ISSUE THREAD

**Issue by DeadSecTr** [anandnet/Harmony-Music#177]
It would be great if the bottom part were also transparent like the top background, so it looks more cohesive without those black bars. The "arrow" can stay as it is.![Screenshot_20240228-234539.png](https://github.com/anandnet/Harmony-Music/assets/90558189/057ea916-3e12-493d-8d63-d709b6452fd7)

**Comment by sudhar08** [comment]
Hey can i  work on this?
