### ISSUE TITLE
   Enabled/disabled color of toggles are misleading.  They should be orange or some color.  Not dull  gray!!. (At Settings )

### ISSUE THREAD

**Issue by blackholeearth** [anandnet/Harmony-Music#178]
**Describe the bug**
Current toggle  colors are reversed. 
 enabled is gray duller color... 
İts misleading...

**To Reproduce**
1. Go to settings 
2. Toggle  enable bottom navbar.
3.  See color is dull gray
4.

**Expected behavior**
 Toggle enabled color is  Orange (or accent color. )
Toggle Disabled color should be gray. 

**Screenshots**

**Smartphone:**
 - Device: [Samsung a12]
 - OS: [ Android 12]

**Additional context**

**Comment by anandnet** [comment]
Fixed in new version.
