### ISSUE TITLE
Release on f-droid

### ISSUE THREAD

**Issue by tvnmguy** [anandnet/Harmony-Music#18]
https://f-droid.org/en/contribute/

**Comment by DickinsonSa** [comment]
Beautifully designed UI, thank you for your efforts.

**Comment by anandnet** [comment]
Created MR for this app  in fdroid data repository : https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13519, Once merged, this app will be available on fdroid.

You can find this app on IzzyOnDroid as well - https://apt.izzysoft.de/fdroid/index/apk/com.anandnet.harmonymusic

**Comment by DickinsonSa** [comment]
Look forward to seeing it there, thanks.

**Comment by anandnet** [comment]
Closing this thread as app is now available on Fdroid - https://f-droid.org/packages/com.anandnet.harmonymusic

**Comment by IzzySoft** [comment]
First congrats to reaching F-Droid, @anandnet! Would be time now to remove your app from my repo, to avoid confusion: you didn't establish reproducible builds with F-Droid (so cross-updates are not possible) – and versionCodes differ a lot (thanks to Flutter's way of creating them, they are +2000 in my repo, resulting in the fact it would be installed from my repo first always without folks being aware).

So can you please remove the badge linking to my repo, to avoid 404s, and then give me a ping here that I can go ahead removing it? Thanks a lot!

**Comment by anandnet** [comment]
@IzzySoft i have removed the badge. Btw we love your repo, thanks for providing us a great app repository:)

**Comment by IzzySoft** [comment]
Thanks! Removed it from my repo then (effective with the next sync). Great to hear your love for my repo :heart_eyes: And of course, should for some reason you need your app back there (e.g. updates stuck at F-Droid for technical reasons), that can be done. All the best for you, and for your project!
