### ISSUE TITLE
Thumbnail is too small

### ISSUE THREAD

**Issue by max5354** [anandnet/Harmony-Music#183]
Plz fix this bug. This looks so weird. Thumbnail looking too much small as shown in screenshot. Plz fix this or implement feature to set the Thumbnail size to MEDIUM LARGE etc....
Android 13
Gakaxy a51
Cpu: v8a

![Screenshot_20240307_193340](https://github.com/anandnet/Harmony-Music/assets/90886938/bcaa3d2a-ad9a-4461-bc8a-2f197960f650)

**Comment by anand-skss** [comment]
will check it

**Comment by anandnet** [comment]
Will check it

**Comment by max5354** [comment]
> Its really too small :D

Yeah!!!

**Comment by max5354** [comment]
@anandnet when will you release new update?

**Comment by anandnet** [comment]
Fixed in new version, check and let me know.
