### ISSUE TITLE
Load laat session is not working 

### ISSUE THREAD

**Issue by max5354** [anandnet/Harmony-Music#184]
Load last session is not working in android 13. Means if we reopen app than it showing nothing even we can't see mini player at bottom .

Device: Galaxy a51
Android :Android 13
Cpu architecture: Arm v8a

**Comment by anand-skss** [comment]
Currently app is saving current session data on exit so you will have to properly exit from app by pressing back button. if you forcibly kill the by swiping then it will not work.

**Comment by anandnet** [comment]
Currently app is saving current session data on exit so you will have to properly exit from app by pressing back button. If you forcibly kill the app by swiping then it will not work

**Comment by max5354** [comment]
> Currently app is saving current session data on exit so you will have to properly exit from app by pressing back button. If you forcibly kill the app by swiping then it will not work

Ohk got it
