### ISSUE TITLE
Android auto

### ISSUE THREAD

**Issue by DickinsonSa** [anandnet/Harmony-Music#19]
Do you have any plans to implement android auto?

**Comment by DickinsonSa** [comment]
Thanks for the update.

**Comment by anandnet** [comment]
@DickinsonSa Android auto support added in v1.3.1.
I have not tasted on real device, hope it will work🤞:) 

Closing for now, if you face any issue please open a issue.

**Comment by DickinsonSa** [comment]
Cool. Missus has a fancy car, so I'll get her to check it out. You're a star 👍
