### ISSUE TITLE
playlists and albums error

### ISSUE THREAD

**Issue by itxmebasit** [anandnet/Harmony-Music#192]
playlists and album not able to fetch stuck on loading screen nothing shows. this error comes in logcat

 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'Map<String, dynamic>'

**Comment by anandnet** [comment]
Thanks for reporting. Today i also observed that. Will fix it.

**Comment by anandnet** [comment]
Fixed in new release.
