### ISSUE TITLE
Showing Black screen

### ISSUE THREAD

**Issue by max5354** [anandnet/Harmony-Music#197]
Showing black screen in latest version whenever i try to exit from app and also Showing black screen when i reopen app.

Using latest version of harmony music 
Android 13
Device : galaxy j8

![Screenshot_20240407_125737](https://github.com/anandnet/Harmony-Music/assets/90886938/de0bd37a-d9c7-46a4-b161-e39a5b1870b1)

**Comment by Sudip339** [comment]
Same is happening in mine

**Comment by yonoff** [comment]
Same issue. Pixel 4a, A13.
Started after update to version 1.9.1.

**Comment by anandnet** [comment]
Fixed in new version
