### ISSUE TITLE
Playlist is not loading 

### ISSUE THREAD

**Issue by max5354** [anandnet/Harmony-Music#198]
In latest version Playlist is not loading means if we share playlist from yt than it is just loading from long time i want to save that Playlist but i can't save just because of loading i tried reinstalling, clear cache and data, and reboot also but it just loading instead of showing songs. My network is also good even i tried wifi but still getting same issue. You can see in screenshot it is just loading i hope you understand and fix it ASAP.

galaxy a51
Android 13
Using latest version of harmony 

![Screenshot_20240407_131115](https://github.com/anandnet/Harmony-Music/assets/90886938/baa51f5c-aa35-4054-8ea8-3a63d34c6f36)

**Comment by anandnet** [comment]
Due to changes in some ytm api, things are breaking. i had applied some fixes. some cases that i'm unaware of need to be fixed. 
it is happening for all playlist?
Could you please provide me playlist name? i'll investigate that.

**Comment by max5354** [comment]
https://youtube.com/playlist?list=PL_o4gdnghKM5MoPXLtWIxFyGjeT1VrBG-

**Comment by Antixlinux** [comment]
In latest update Harmony doesn't working well 😔

**Comment by anandnet** [comment]
Fixed, you may check now
