### ISSUE TITLE
Shuffle

### ISSUE THREAD

**Issue by NormalLeon** [anandnet/Harmony-Music#199]
Please add a shuffle button for playlists

**Comment by sudhar08** [comment]
Hey can i work on this

**Comment by MCRMAURI** [comment]
Shuffle button please

**Comment by jacobot1** [comment]
There is already a shuffle button in the Queue. After you queue up a playlist, you can press that and it will shuffle.

**Comment by anandnet** [comment]
And You can also enable shuffle mode from player screen
