### ISSUE TITLE
Add song information in player

### ISSUE THREAD

**Issue by itxmebasit** [anandnet/Harmony-Music#201]
add song info button where we get details about song like id, cache, loudness, bitrate etc

for more reference check ss
![SmartSelect_20240409_135841](https://github.com/anandnet/Harmony-Music/assets/166026409/36bbc5d9-541d-491e-91a3-67e11e7b0c0d)

**Comment by itxmebasit** [comment]
@anandnet check??

**Comment by anandnet** [comment]
Hi @itxmebasit , unfortunately, i am bit busy these days in some other work. As soon as i have some free time i will look at this.
