### ISSUE TITLE
Albums not loading

### ISSUE THREAD

**Issue by elerion1992** [anandnet/Harmony-Music#209]
When I look for an artist and then I go to Albums it stays loading forever. It also happens with playlists. However, songs are loaded. I'm using last version of the program.
![Screenshot_2024-04-14-22-48-06-963_com anandnet harmonymusic](https://github.com/anandnet/Harmony-Music/assets/167032979/9ee67a4b-4c09-4338-a05a-f226ae9ac0b6)
Smartphone info:

![Screenshot_2024-04-14-22-49-14-642_com android settings](https://github.com/anandnet/Harmony-Music/assets/167032979/4c0944c5-1281-4b78-b57b-052cc5af6233)

**Comment by encryptionstudio** [comment]
Me too
