### ISSUE TITLE
Language options 

### ISSUE THREAD

**Issue by senolfndk** [anandnet/Harmony-Music#21]
Can you add Turkish language

**Comment by anandnet** [comment]
@senolfndk  Turkish language is now available in v1.6.0.

**Comment by senolfndk** [comment]
> @senolfndk Türkçe dili artık v1.6.0'da mevcut.
ok thank you

**Comment by senolfndk** [comment]
> @senolfndk Türkçe dili artık v1.6.0'da mevcut.

ok thank you @anandnet
