### ISSUE TITLE
Can i enable lyrics on desktop any way?

### ISSUE THREAD

**Issue by NikunjKhangwal** [anandnet/Harmony-Music#226]
I can't find any option to see lyrics on pc version. Does the app not support it yet or i'm missing something?

**Comment by TMCsgs** [comment]
I am using Linux but i guess it should be the same for other operating systems:
If you resize the window to a handy-like format and click on the bottom bar with the Title and the play/pause buttons the cover should get bigger. If you click on it the lyrics should be shown.
Btw if you click on that arrow on the bottom you can shuffle the playlist too.

**Comment by NikunjKhangwal** [comment]
Thanks, I'll try it
