### ISSUE TITLE
Loop play queue option is missing

### ISSUE THREAD

**Issue by yonoff** [anandnet/Harmony-Music#234]
At the moment there is no way to repeat/loop a playlist; playback stops after playing the last track in the queue. It would be great to add a drop-down menu to the infinity button to select between a looped track or a looped playlist. Or add a loop queue option to the app settings.

**Comment by ImTheLeviDR** [comment]
I really miss this

**Comment by anandnet** [comment]
Available now in new version

**Comment by yonoff** [comment]
Can you make it available for Radio mode too?

**Comment by anandnet** [comment]
Radio mode has endless queue, so loop cannot be enabled , when it reaches
to last song of queue append another set of random song so it becomes never
ending queue.

**Comment by yonoff** [comment]
Got it, thanks for explaining

**Comment by yonoff** [comment]
Regarding the radio, it doesn't really work as a radio. Launching the radio actually creates a playlist of ~50 tracks that doesn't extend automatically and playback stops after the last track. I think it would be better to have the option to turn on a loop for the radio too, as is present in similar apps (ViTune, InnerTune, RiMusic).

**Comment by anandnet** [comment]
It seems, you are using radio in shuffle mode. Note that in shuffle mode last song of list is not the actual last, it would be randomly any song, my advice would be that please turn of shuffle mode then start radio mode if you want this behavior.

**Comment by yonoff** [comment]
I don't think I don't turn on the shuffle.

There are two buttons with a shuffle icon in the app:
One at the bottom next to the play and rewind buttons, and it's off. 
The second one appears in the upper right corner when you turn on playlist viewing. I don't quite understand what it does, it seems to just shuffle the tracks in the playlist once.
I'm using the latest version of the app (v1.10.4) on Ubuntu (versions 22.04 and 24.04) and the radio stops playing after the last track in the playlist is played, despite the shuffle button at the bottom being off.

![harmony-music](https://github.com/user-attachments/assets/3c73e43f-d216-4b38-9d54-203b6ed05fa4)

**Comment by yonoff** [comment]
upd.

To my delight, after I pressed the button in the upper right corner a few times, the radio started playing the endless stream as you described.
Could you please explain how exactly this works?
And is there a way to make this button appear greyed out when disabled 
because there is currently no indication whether it is enabled or not.
![image](https://github.com/user-attachments/assets/0fdd4c6c-6b19-4544-a3f7-390ea9d9c5cd)
