### ISSUE TITLE
Import Spotify playlists

### ISSUE THREAD

**Issue by korzor** [anandnet/Harmony-Music#238]
Thank you.

**Comment by anandnet** [comment]
it is out of scope, it requires spotify login. Currently not have any plan to implement it.

**Comment by korzor** [comment]
i mean Manually import manually exported playlists , no need to log in Spotify. Thanks for your work <3

**Comment by anandnet** [comment]
Is there any way we can export playlist manually from spotify?

**Comment by korzor** [comment]
I'm sorry, I made a mistake. I thought it was possible to export a list
with the songs and their artists, but it's just a link to the list itself,
which opens either in Spotify or in a browser. I don't know, but maybe
there's a way to interpret everything that appears in the browser and
extract the text of the song titles, but I suppose it would be too
complicated to do that.
