### ISSUE TITLE
Sleep timer in mobile application 

### ISSUE THREAD

**Issue by foglar** [anandnet/Harmony-Music#240]
I want to listen to music before sleep. Currently I cannot find any way to turn music off after a certain period of time like in the Spotube (very similar music application, using Spotify to synchronize). I would like to pick after what time music should stop (10 min, 15 min, 30 min) playing. I cannot find any other way of setting this in the application.
![Screenshot_20240626-000542.jpg](https://github.com/anandnet/Harmony-Music/assets/82380203/d97a4b84-b85e-403f-bb91-66ca837709a0)![Screenshot_20240626-000606.png](https://github.com/anandnet/Harmony-Music/assets/82380203/9fa51452-2ab6-4a22-87ba-2b24647e5e41)

**Comment by encryptionstudio** [comment]
nice rickroll xD

**Comment by anandnet** [comment]
@foglar just give a long press on album art img on player screen you will see option for sleep timer.![Screenshot_20240626_131558.jpg](https://github.com/anandnet/Harmony-Music/assets/45705030/2bd62480-71fa-4017-b2a9-f72bee607d52)
