### ISSUE TITLE
Temporizador para el apagado automático 

### ISSUE THREAD

**Issue by Ivanaix** [anandnet/Harmony-Music#245]
**Is your feature request related to a problem or new idea? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] or new idea

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by anandnet** [comment]
Hello @Ivanaix , please check https://github.com/anandnet/Harmony-Music/issues/240#issuecomment-2191043764
