### ISSUE TITLE
Doesn't play some songs

### ISSUE THREAD

**Issue by Ivanaix** [anandnet/Harmony-Music#247]
![Screenshot_20240713_224708_com anandnet harmonymusic](https://github.com/user-attachments/assets/cf677f06-3126-4171-b6ba-13ce06fd97a2)

**Comment by bellatrix-8** [comment]
This song cannot be played due to server restrictions. This is not an issue with the app.

**Comment by bellatrix-8** [comment]
https://github.com/user-attachments/assets/972323a0-767d-4bf4-bd3c-ed5cdff940a4

No, Rimusic doesn't play this song. It says "This song cannot be played due to server restrictions." Maybe the app connects to a different server every time.

**Comment by anandnet** [comment]
Thanks @bellatrix-8 for your research on this topic, this is really helpful 😄 . Closing this one.
