### ISSUE TITLE
Unable to play any song.

### ISSUE THREAD

**Issue by igov23** [anandnet/Harmony-Music#248]
**Describe the bug**
The app cannot play any song online, it just allow to play previously downloaded songs.

**To Reproduce**
1. Go to main screen
2. Click on any song or search for any song
3. The player tries to load the song
4. The player just keeps loading forever

**Expected behavior**
The song should start playing as usual

**Screenshots**
![Screenshot_20240816-082055_Harmony Music](https://github.com/user-attachments/assets/4e38d48f-2e53-41f3-a14b-9252517bf497)

**Smartphone (please complete the following information):**
 - Device: Motorola One Fusion+
 - OS: Android 13 Lineage OS 20

**Additional context**
Maybe this is related to recent problems with piped connections but cannot find any information related to Harmony being affected by this piped service issue.

**Comment by anandnet** [comment]
No, it doesn't depend on Piped for streaming. I have checked in multiple devices everything is working fine. there might be internet issue, you can try with wifi/different data connection. Closing for now, you can reopen if still facing this issue.
