### ISSUE TITLE
Backup and restore feature on Android 

### ISSUE THREAD

**Issue by IamArman2007** [anandnet/Harmony-Music#250]
**Is your feature request related to a problem or new idea? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] or new idea

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by encrystudio** [comment]
I already tried implementing it on android, but there are some problems with permission and file handing. That's why it's currently windows only. If I have free time, I can try it again
