### ISSUE TITLE
Add Album Info and Artwork To Export

### ISSUE THREAD

**Issue by ajk-47** [anandnet/Harmony-Music#257]
**Is your feature request related to a problem or new idea? Please describe.**
A clear and concise description of what the problem is. 
When I export songs, the files do not have any metadata present in the harmony player, such as the album artwork and album name and artist name. That would be an epicsauce addition.

**Describe the solution you'd like**
I would love it if this were able to be implemented into the metadata of the exported song. (Just as it can be added in windows media player or through the android app musicolet and others)

**Describe alternatives you've considered**
Adding this info manually seems unnecessary, as it is all accessible and present in the app.
**Additional context**

**Comment by anandnet** [comment]
it is already there, note that you should select m4a format from settings before downloading any song. it is not available for opus.
please try this, reopen if it it not working or let me know if you have question.
