### ISSUE TITLE
Alternative Linux packages (RPM, AppImage, Flatpak)

### ISSUE THREAD

**Issue by systemd11** [anandnet/Harmony-Music#259]
**Is your feature request related to a problem or new idea? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] or new idea

i would like to have alternative Linux packaging formats like RPM, Flatpak or AppImage.

**Describe the solution you'd like**

Compile it for other distributions.

**Describe alternatives you've considered**

-

**Additional context**

**Comment by anandnet** [comment]
for now use https://github.com/anandnet/build-HM - Actions to build RPM (Not tested), AppImage
