### ISSUE TITLE
Remove old queue when choosing to play a new playlist

### ISSUE THREAD

**Issue by andreatede2002** [anandnet/Harmony-Music#260]
I'm always frustrated when I play a playlist and it mixes up with the pre-existing queue.

I want the new playlist to replace the one I was listening before (just like Spotify)

Another option could be adding a button that clears the previous queue.

Best regards

**Comment by anandnet** [comment]
Just play any song from new playlist it will replace whole queue with new playlist songs. If you enqueue, it will append the new playlist songs tob the current queue.
