### ISSUE TITLE
Item slide gesture for common tasks

### ISSUE THREAD

**Issue by encrystudio** [anandnet/Harmony-Music#265]
**Is your feature request related to a problem or new idea? Please describe.**
New idea.

**Describe the solution you'd like**
It's annoying to always have to open the context menu to add a song to the queue or do other common tasks. I'd like faster and more intuitive way to do these, like a swipe gesture with common tasks like "Play Next", "Remove from Playlist" and "Add to Playlist". 

**Describe alternatives you've considered**
Alternatively it could be only the "Play Next" feature, which would work like on Spotify (swipe the item and it will be added as next).

**Additional context**
I think the ``flutter_slidable`` package is a good and easy choice to implement this.

**Comment by anandnet** [comment]
indeed its a good idea, i was also thinking of building complete gesture based player screen, but i have very limited time to manage all this. After looking at the floods of issues , i though to give some time for fixes and new release. Will try to implement if have free time.

**Comment by DarkNinja15** [comment]
@anandnet 
Hi there!!, Can I handle this issue ?

**Comment by anandnet** [comment]
Yes,please

**Comment by DarkNinja15** [comment]
@anandnet I have raised a PR. Please review it.

**Comment by DarkNinja15** [comment]
@anandnet  This issue is resolved and can be closed now.
