### ISSUE TITLE
Stop music on task clear not working

### ISSUE THREAD

**Issue by Linok-B** [anandnet/Harmony-Music#268]
**Issue**
Since the recent 1.10.0 android update, the "Stop music on task clear" no longer works (at least on my device)

**Expected behavior**
The app being cleared and the music to stop playing, as well as any sessions.

**Smartphone:**
 - Device: RealMe 30 (or 31, can't remember nor find it on settings.)
 - OS: Android 11

**Additional info:**
I have updated the app using the 1.10.0 universal apk.

**Comment by anandnet** [comment]
i have also observed this. Will look into code an try to fix it.

**Comment by anandnet** [comment]
Fixed now
