### ISSUE TITLE
Multiple entries of same song in Recently played

### ISSUE THREAD

**Issue by Apsinghsa** [anandnet/Harmony-Music#269]
In windows version, problem got fixed, but in android app, problem is still there

**Comment by anandnet** [comment]
That would be songs played in older version. If you now play the same song you will observe duplicate entries will be removed.

**Comment by Apsinghsa** [comment]
No bro, I downloaded the app yesterday in my phone, after update

**Comment by Apsinghsa** [comment]
Maybe because I downloaded from f-droid

**Comment by Apsinghsa** [comment]
Yes, F-droid have older version

**Comment by anandnet** [comment]
Fdroid usually takes some (3-4 days) time to reflect/release new version.
