### ISSUE TITLE
Prettify title on Windows app

### ISSUE THREAD

**Issue by jacobot1** [anandnet/Harmony-Music#279]
**Is your feature request related to a problem or new idea? Please describe.**
Not a problem, just an idea

**Describe the solution you'd like**
This is quite insignificant, but I think it would look better if the window title on Windows said "Harmony Music" instead of harmonymusic.

**Describe alternatives you've considered**
Leave it if it's not worth the trouble.

**Additional context**

![image](https://github.com/user-attachments/assets/489c9106-bcee-4fb1-a17e-894b516473bb)

**Comment by anandnet** [comment]
Done
