### ISSUE TITLE
AppImage don't play

### ISSUE THREAD

**Issue by als-creator** [anandnet/Harmony-Music#281]
**Describe the bug**
AppImage don't play  music

**To Reproduce**
<details>
  <summary>Подробнее</summary>
/mnt/Data/Distrib/Linux/AppImage/harmonymusicv1.10.0_7f5ab5c75788ad25c1ea3c8426a347a6.AppImage
package:media_kit_libs_linux registered.
flutter: 
--------------------------------------------------------------------------------
media_kit: ERROR: MediaKit.ensureInitialized
This indicates that one or more required dependencies could not be located.

Refer to "Installation" section of the README for further details:
GitHub  : https://github.com/media-kit/media-kit#installation
pub.dev : https://pub.dev/packages/media_kit#installation

TIP: Copy-paste required packages from the above link to your pubspec.yaml.

If you recently added the packages, make sure to re-run the project ("hot-restart" & "hot-reload" is not sufficient for native plugins).
--------------------------------------------------------------------------------

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Cannot find libmpv at the usual places. Depending upon your distribution, you can install the libmpv package to make shared library available globally. On Debian or Ubuntu based systems, you can install it with: apt install libmpv-dev.
#0      NativeLibrary.ensureInitialized (package:media_kit/src/player/native/core/native_library.dart:79)
#1      nativeEnsureInitialized (package:media_kit/src/player/native/player/real.dart:47)
#2      MediaKit.ensureInitialized (package:media_kit/src/media_kit.dart:30)
#3      JustAudioMediaKit.init (package:just_audio_media_kit/just_audio_media_kit.dart:41)
#4      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1401)
#5      AudioPlayer._setPlatformActive (package:just_audio/just_audio.dart:1517)
#6      AudioPlayer.load (package:just_audio/just_audio.dart:809)
#7      AudioPlayer.setAudioSource (package:just_audio/just_audio.dart:780)
#8      MyAudioHandler._addEmptyList (package:harmonymusic/services/audio_handler.dart:94)
#9      new MyAudioHandler (package:harmonymusic/services/audio_handler.dart:68)
#10     initAudioService.<anonymous closure> (package:harmonymusic/services/audio_handler.dart:27)
#11     AudioService.init (package:audio_service/audio_service.dart:1009)
<asynchronous suspension>
#12     initAudioService (package:harmonymusic/services/audio_handler.dart:26)
<asynchronous suspension>
#13     main (package:harmonymusic/main.dart:31)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Cannot find libmpv at the usual places. Depending upon your distribution, you can install the libmpv package to make shared library available globally. On Debian or Ubuntu based systems, you can install it with: apt install libmpv-dev.
#0      NativeLibrary.ensureInitialized (package:media_kit/src/player/native/core/native_library.dart:79)
#1      nativeEnsureInitialized (package:media_kit/src/player/native/player/real.dart:47)
#2      MediaKit.ensureInitialized (package:media_kit/src/media_kit.dart:30)
#3      JustAudioMediaKit.init (package:just_audio_media_kit/just_audio_media_kit.dart:41)
#4      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1401)
#5      AudioPlayer._setPlatformActive (package:just_audio/just_audio.dart:1517)
#6      AudioPlayer.load (package:just_audio/just_audio.dart:809)
#7      AudioPlayer.setAudioSource (package:just_audio/just_audio.dart:780)
#8      MyAudioHandler._addEmptyList (package:harmonymusic/services/audio_handler.dart:94)
#9      new MyAudioHandler (package:harmonymusic/services/audio_handler.dart:68)
#10     initAudioService.<anonymous closure> (package:harmonymusic/services/audio_handler.dart:27)
#11     AudioService.init (package:audio_service/audio_service.dart:1009)
<asynchronous suspension>
#12     initAudioService (package:harmonymusic/services/audio_handler.dart:26)
<asynchronous suspension>
#13     main (package:harmonymusic/main.dart:31)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Cannot find libmpv at the usual places. Depending upon your distribution, you can install the libmpv package to make shared library available globally. On Debian or Ubuntu based systems, you can install it with: apt install libmpv-dev.
#0      NativeLibrary.ensureInitialized (package:media_kit/src/player/native/core/native_library.dart:79)
#1      nativeEnsureInitialized (package:media_kit/src/player/native/player/real.dart:47)
#2      MediaKit.ensureInitialized (package:media_kit/src/media_kit.dart:30)
#3      JustAudioMediaKit.init (package:just_audio_media_kit/just_audio_media_kit.dart:41)
#4      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1401)
#5      AudioPlayer._setPlatformActive (package:just_audio/just_audio.dart:1517)
#6      AudioPlayer.load (package:just_audio/just_audio.dart:809)
#7      AudioPlayer.setAudioSource (package:just_audio/just_audio.dart:780)
#8      MyAudioHandler._addEmptyList (package:harmonymusic/services/audio_handler.dart:94)
#9      new MyAudioHandler (package:harmonymusic/services/audio_handler.dart:68)
#10     initAudioService.<anonymous closure> (package:harmonymusic/services/audio_handler.dart:27)
#11     AudioService.init (package:audio_service/audio_service.dart:1009)
<asynchronous suspension>
#12     initAudioService (package:harmonymusic/services/audio_handler.dart:26)
<asynchronous suspension>
#13     main (package:harmonymusic/main.dart:31)
<asynchronous suspension>

</details>
**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/a876a356-3805-4cad-a874-9a34d905c76c)

**Smartphone (please complete the following information):**
OS: Arch Linux (x86_64)
Kernel: Linux 6.10.10-x64v2-xanmod1-1-x64v2
Uptime: 19 hours, 14 mins
DE: Xfce4 4.18
Shell: zsh 5.9
Terminal: guake
Display (VSC6B2F): 1920x1080 @ 60 Hz in 23″ [External]
CPU: AMD A10 PRO-7800B R7, 12 Compute Cores 4C+8G (4) @ 3.50 GHz
GPU: AMD Radeon R7 Graphics [Discrete]
OpenGL: 4.5 (Compatibility Profile) Mesa 24.2.2-arch1.1

**Additional context**

**Comment by anandnet** [comment]
It seems mpv package is not installed on your system. I don't how to install on arch linux could you please try installing mpv ? Here is package details https://archlinux.org/packages/extra/x86_64/mpv/

**Comment by als-creator** [comment]
mpv installed
local/mpv 1:0.38.0-8
    a free, open source, and cross-platform media player

**Comment by als-creator** [comment]
I've been using mpv for a long time and this image doesn't work

**Comment by anandnet** [comment]
Ok No worries, may be i will try to include libmpv.so, while building new appimage binary.

**Comment by devaex** [comment]
Same problem here.

MPV is installed
mpv 0.38.0+git20240706.00f43e0916fa Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects

OS: OpenSuse TumbleWeed.

**Comment by devaex** [comment]
Installed the rpm version and same error, don't play.

Launched in terminal and get this error:

```
package:media_kit_libs_linux registered.
flutter: 
--------------------------------------------------------------------------------
media_kit: ERROR: MediaKit.ensureInitialized
This indicates that one or more required dependencies could not be located.

Refer to "Installation" section of the README for further details:
GitHub  : https://github.com/media-kit/media-kit#installation
pub.dev : https://pub.dev/packages/media_kit#installation

TIP: Copy-paste required packages from the above link to your pubspec.yaml.

If you recently added the packages, make sure to re-run the project ("hot-restart" & "hot-reload" is not sufficient for native plugins).
--------------------------------------------------------------------------------

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Cannot find libmpv at the usual places. Depending upon your distribution, you can install the libmpv package to make shared library available globally. On Debian or Ubuntu based systems, you can install it with: apt install libmpv-dev.
#0      NativeLibrary.ensureInitialized (package:media_kit/src/player/native/core/native_library.dart:79)
#1      nativeEnsureInitialized (package:media_kit/src/player/native/player/real.dart:47)
#2      MediaKit.ensureInitialized (package:media_kit/src/media_kit.dart:30)
#3      JustAudioMediaKit.init (package:just_audio_media_kit/just_audio_media_kit.dart:41)
#4      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1401)
#5      AudioPlayer._setPlatformActive (package:just_audio/just_audio.dart:1517)
#6      AudioPlayer.load (package:just_audio/just_audio.dart:809)
#7      AudioPlayer.setAudioSource (package:just_audio/just_audio.dart:780)
#8      MyAudioHandler._addEmptyList (package:harmonymusic/services/audio_handler.dart:94)
#9      new MyAudioHandler (package:harmonymusic/services/audio_handler.dart:68)
#10     initAudioService.<anonymous closure> (package:harmonymusic/services/audio_handler.dart:27)
#11     AudioService.init (package:audio_service/audio_service.dart:1009)
<asynchronous suspension>
#12     initAudioService (package:harmonymusic/services/audio_handler.dart:26)
<asynchronous suspension>
#13     main (package:harmonymusic/main.dart:31)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Cannot find libmpv at the usual places. Depending upon your distribution, you can install the libmpv package to make shared library available globally. On Debian or Ubuntu based systems, you can install it with: apt install libmpv-dev.
#0      NativeLibrary.ensureInitialized (package:media_kit/src/player/native/core/native_library.dart:79)
#1      nativeEnsureInitialized (package:media_kit/src/player/native/player/real.dart:47)
#2      MediaKit.ensureInitialized (package:media_kit/src/media_kit.dart:30)
#3      JustAudioMediaKit.init (package:just_audio_media_kit/just_audio_media_kit.dart:41)
#4      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1401)
#5      AudioPlayer._setPlatformActive (package:just_audio/just_audio.dart:1517)
#6      AudioPlayer.load (package:just_audio/just_audio.dart:809)
#7      AudioPlayer.setAudioSource (package:just_audio/just_audio.dart:780)
#8      MyAudioHandler._addEmptyList (package:harmonymusic/services/audio_handler.dart:94)
#9      new MyAudioHandler (package:harmonymusic/services/audio_handler.dart:68)
#10     initAudioService.<anonymous closure> (package:harmonymusic/services/audio_handler.dart:27)
#11     AudioService.init (package:audio_service/audio_service.dart:1009)
<asynchronous suspension>
#12     initAudioService (package:harmonymusic/services/audio_handler.dart:26)
<asynchronous suspension>
#13     main (package:harmonymusic/main.dart:31)
```

**Comment by trunars** [comment]
> Инсталирах rpm версията и същата грешка, не играй.
> 
> Стартирах в терминала и получих тази грешка:
> 
> ```
> package:media_kit_libs_linux registered.
> flutter: 
> --------------------------------------------------------------------------------
> media_kit: ERROR: MediaKit.ensureInitialized
> This indicates that one or more required dependencies could not be located.
> 
> Refer to "Installation" section of the README for further details:
> GitHub  : https://github.com/media-kit/media-kit#installation
> pub.dev : https://pub.dev/packages/media_kit#installation
> 
> TIP: Copy-paste required packages from the above link to your pubspec.yaml.
> 
> If you recently added the packages, make sure to re-run the project ("hot-restart" & "hot-reload" is not sufficient for native plugins).
> --------------------------------------------------------------------------------
> 
> [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Cannot find libmpv at the usual places. Depending upon your distribution, you can install the libmpv package to make shared library available globally. On Debian or Ubuntu based systems, you can install it with: apt install libmpv-dev.
> #0      NativeLibrary.ensureInitialized (package:media_kit/src/player/native/core/native_library.dart:79)
> #1      nativeEnsureInitialized (package:media_kit/src/player/native/player/real.dart:47)
> #2      MediaKit.ensureInitialized (package:media_kit/src/media_kit.dart:30)
> #3      JustAudioMediaKit.init (package:just_audio_media_kit/just_audio_media_kit.dart:41)
> #4      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1401)
> #5      AudioPlayer._setPlatformActive (package:just_audio/just_audio.dart:1517)
> #6      AudioPlayer.load (package:just_audio/just_audio.dart:809)
> #7      AudioPlayer.setAudioSource (package:just_audio/just_audio.dart:780)
> #8      MyAudioHandler._addEmptyList (package:harmonymusic/services/audio_handler.dart:94)
> #9      new MyAudioHandler (package:harmonymusic/services/audio_handler.dart:68)
> #10     initAudioService.<anonymous closure> (package:harmonymusic/services/audio_handler.dart:27)
> #11     AudioService.init (package:audio_service/audio_service.dart:1009)
> <asynchronous suspension>
> #12     initAudioService (package:harmonymusic/services/audio_handler.dart:26)
> <asynchronous suspension>
> #13     main (package:harmonymusic/main.dart:31)
> <asynchronous suspension>
> ```

sudo dnf install mpv-libs
sudo dnf install mpv-devel
sudo ln -s /usr/lib64/libmpv.so /usr/lib64/libmpv.so.1

**Comment by CHPgmz** [comment]
I get the same error, when I run the version in 'appImage' it does not find the package/library 'libmpv-dev.', even though I have them installed, I am running in manjaro linux:

`If you recently added the packages, make sure to re-run the project ("hot-restart" & "hot-reload" is not sufficient for native plugins).
--------------------------------------------------------------------------------

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Cannot find libmpv at the usual places. Depending upon your distribution, you can install the libmpv package to make shared library available globally. On Debian or Ubuntu based systems, you can install it with: apt install libmpv-dev.
#0      NativeLibrary.ensureInitialized (package:media_kit/src/player/native/core/native_library.dart:79)
#1      nativeEnsureInitialized (package:media_kit/src/player/native/player/real.dart:47)
#2      MediaKit.ensureInitialized (package:media_kit/src/media_kit.dart:30)
#3      JustAudioMediaKit.init (package:just_audio_media_kit/just_audio_media_kit.dart:41)
#4      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1401)
#5      AudioPlayer._setPlatformActive (package:just_audio/just_audio.dart:1517)
#6      AudioPlayer.load (package:just_audio/just_audio.dart:809)
#7      AudioPlayer.setAudioSource (package:just_audio/just_audio.dart:780)
#8      MyAudioHandler._addEmptyList (package:harmonymusic/services/audio_handler.dart:94)
#9      new MyAudioHandler (package:harmonymusic/services/audio_handler.dart:68)
#10     initAudioService.<anonymous closure> (package:harmonymusic/services/audio_handler.dart:27)
#11     AudioService.init (package:audio_service/audio_service.dart:1009)
<asynchronous suspension>
#12     initAudioService (package:harmonymusic/services/audio_handler.dart:26)
<asynchronous suspension>
#13     main (package:harmonymusic/main.dart:31)
<asynchronous suspension>`

**Comment by anandnet** [comment]
it is happening due to mismatching of some libraries version, i have removed those libs from appImage bin and it is working fine. i will release a new version soon with.    you can also built and test fixed one by yourself using git action https://github.com/anandnet/build-HM   - > follow the description steps

**Comment by anandnet** [comment]
Hi everyone, please check new released appimage binary. Let me know if still you are facing this issue

**Comment by quazar-omega** [comment]
I'm on version 1.10.2 and I'm still having the same issue

**Comment by anandnet** [comment]
Please install mpv:

For Debian:
sudo apt install mpv

For Arch linux:
sudo pacman -s mpv

For Red hat:
sudo dnf install mpv-libs

**Comment by quazar-omega** [comment]
Oh, I thought you ended up bundling it with the application itself.  
Then I'll try again with that and let you know

**Comment by devaex** [comment]
I tested the appimage on Linux Mint/Ubuntu and I confirm that everything is ok now.

Great app.

**Comment by quazar-omega** [comment]
Works for me too on Kinoite after installing `mpv-libs`

```sh
rpm-ostree install mpv-libs
```

Love it!

Btw, I first tried installing mpv through home manager but it didn't work, so I had to layer the package, know if it's possible to get it to work with the Nix one?
