### ISSUE TITLE
Song is not playable due to server restriction! — harmful content

### ISSUE THREAD

**Issue by Linok-B** [anandnet/Harmony-Music#287]
**The bug in question:**
You cannot reproduce songs from YouTube that have the following warning pop-up before the video is played (the warning has been translated by myself from Spanish): 

> **Warning: The content on this video may harm the user's sensibility.**
The following video may contain topics related to suicide or self-harm.

**To Reproduce**
1. Try to reproduce the following song through HarmonyMusic:
>> https://youtu.be/DvYQpplzmzY?si=eXTJ6kzSuHzgFlbt

2. Does not work

**Expected behavior**
Two options:

1. The app automatically ignores this thing and plays the song, no server error.
2. The app displays a pop-up with this warning, asking the user to confirm or deny. There will also be a setting which will allow the user to select whether they want to have this pop-up appear or always accept it.

**Smartphone**
 - Device: Realme C30
 - OS: Android 11

**Additional context**
ngl very annoying

**Comment by anandnet** [comment]
I'm sorry, I believe that requires lot of work for this small thing. Alternatively you can play song version of this song which is playable instead of video version https://youtube.com/watch?v=LSfl7AWW7ak.

**Comment by Linok-B** [comment]
> I'm sorry, I believe that requires lot of work for this small thing. Alternatively you can play song version of this song which is playable instead of video version https://youtube.com/watch?v=LSfl7AWW7ak.

The thing is, I don't recall experiencing this issue on the 1.9.2 version.

**Comment by anandnet** [comment]
Yes, the package was different that's why. I was unable to implement some functionality due to less info available, and also stream url return time was high so i had to remove.
