### ISSUE TITLE
Song is not playable due to server restriction!

### ISSUE THREAD

**Issue by jerry-619** [anandnet/Harmony-Music#291]
songs not playing when using vpn in previous version this issue didn't occur

**Comment by anandnet** [comment]
I suspect this could be related to #292.

**Comment by anandnet** [comment]
https://github.com/user-attachments/assets/e1a16da3-134f-4653-a186-d8be355e5127

@jerry-619  Tried and it is working fine for me

**Comment by anandnet** [comment]
Try new version, it might work.

**Comment by anandnet** [comment]
This has been fixed now, but may occur when vpn will be used.
