### ISSUE TITLE
YouTube Licensing Debauchal

### ISSUE THREAD

**Issue by jacobot1** [anandnet/Harmony-Music#292]
This is not a bug in the app, but in YouTube itself.

YouTube just removed thousands of songs on its US site from hundreds of artists including quite popular ones like Smells Like Teen Spirit by Nirvana. This happened because YouTube's deal with SESAC, a music licensing company, expired before they renewed it properly.

The repercussions for us are that anytime we search a song in Harmony Music that has been removed from YouTube, a blank search screen is shown.

One workaround that I have successfully used is a VPN. If I connect to a VPN like Proton and connect to a non-US server, everything works properly.

Hopefully YouTube will resolve this issue VERY soon because it's a MAJOR blow to their business.

**Comment by nanderer** [comment]
Maybe build in a piped feature to use one of those YouTube proxys
