### ISSUE TITLE
don't loose current playback queue accidentally 

### ISSUE THREAD

**Issue by nanderer** [anandnet/Harmony-Music#294]
I had it a couple times I hit a song somewhere in the search results or on an album view and that replaced my entire playback queue with no way to get it back. Maybe add an are you sure question like spotube dose. ( And if you are looking up there code maybe copy the Songtext Feature ;) )

Normally I want to enque songs I select, either play next or put it at the end.

Also the ability to save an queue as a Playlist would be nice

**Comment by anandnet** [comment]
You can long press on song tile to enqueue or play next from context menu or slide left song tile you will see options.
