### ISSUE TITLE
Optional feature: Gesture based player (Android)

### ISSUE THREAD

**Issue by anandnet** [anandnet/Harmony-Music#296]
## Controls:
<b>Swipe left:</b> Next track
<b>Swipe right:</b> Prev track
<b>Swipe Up:</b> Current queue
<b>Swipe Down:</b> Minimize player
<b>Double Tap:</b> Pause/Play
<b>Long Press:</b> Context menu for current song

**Comment by yakupkahraman** [comment]
The most creative touch i've ever seen. It's obviously perfect ui.

**Comment by yakupkahraman** [comment]
I found a problem. Where is lyrics? :D
