### ISSUE TITLE
Incomplete translation?

### ISSUE THREAD

**Issue by Mickael81** [anandnet/Harmony-Music#298]
When I open the app, I noticed that some elements on the home page (circled in red in the screenshot) were not translated and were still displayed in English. Is this normal? Can we translate them?
![Screenshot_20241009_175911](https://github.com/user-attachments/assets/e967c279-11ee-448e-860e-9fff0765e581)

**Comment by Mickael81** [comment]
Thank you very much for fixing this small translation issue. 😉👌

**Comment by Mickael81** [comment]
Unfortunately, the problem is still present when I open the application on Android. 😕
![Screenshot_20241020_000412](https://github.com/user-attachments/assets/b238461b-fe3c-4747-9603-4a5b2822d1f1)

**Comment by anandnet** [comment]
Try changing it en first and then french. It will probably reset it

**Comment by Mickael81** [comment]
Thank you very much. I tried it and it worked. 👍
