### ISSUE TITLE
Even after closing the app from recent tasks, songs continues to play 

### ISSUE THREAD

**Issue by dainvincible1** [anandnet/Harmony-Music#30]
Even after closing the app from recent tasks, the song continues to play. Battery optimization is enabled

https://github.com/anandnet/Harmony-Music/assets/127825700/df86419f-0622-4dc1-858e-ee863b093f9a

**Comment by anandnet** [comment]
Hello @dainvincible1  i believe its not a bug, it comes under feature Background playling.

if you want to add i can try  to add a option in settings which would ensure that music playback stop when app will be cleared from ram.

**Comment by dainvincible1** [comment]
> Hello @dainvincible1 i believe its not a bug, it comes under feature Background playling.
> 
> if you want to add i can try to add a option in settings which would ensure that music playback stop when app will be cleared from ram.

yeeep, that would be so awesome. thank you so much

**Comment by dainvincible1** [comment]
> Hello @dainvincible1 i believe its not a bug, it comes under feature Background playling.
> 
> if you want to add i can try to add a option in settings which would ensure that music playback stop when app will be cleared from ram.

@anandnet  yeeep, that would be so awesome. thank you so much

**Comment by anandnet** [comment]
added in v1.4.0, please check
