### ISSUE TITLE
Program not starting

### ISSUE THREAD

**Issue by TMCsgs** [anandnet/Harmony-Music#309]
I installed Version 1.10.2.

I tried to start harmony over the taskbar icon and it did not start.

when I start it in the terminal this error is produced:
/usr/bin/harmonymusic: symbol lookup error: /usr/bin/harmonymusic: undefined symbol: g_once_init_enter_pointer

**Device:**
Linux Mint Cinnamon

**Comment by anandnet** [comment]
- Updated binaries in release section, please try now
