### ISSUE TITLE
Typo: "Disblaled" -> "Disabled"

### ISSUE THREAD

**Issue by inflationsbereinigt** [anandnet/Harmony-Music#33]
Tiny typo I noticed in the settings, "disblaled" should be "disabled":

https://github.com/anandnet/Harmony-Music/blob/6d938c557e71e4368d8abf515d14d32358b77fb7/lib/ui/screens/settings_screen.dart#L176

Thanks for this app!

**Comment by anandnet** [comment]
Yeah, i have also noticed that :smile: . will fix soon in app localization implementation.
Btw thanks for reporting.

**Comment by anandnet** [comment]
Closing as corrected in v1.3.2.
