### ISSUE TITLE
Sometimes songs dont play even after waiting for a long time

### ISSUE THREAD

**Issue by dainvincible1** [anandnet/Harmony-Music#34]
https://github.com/anandnet/Harmony-Music/assets/127825700/d0cadd0f-5fa8-4ebd-a6a2-d8870fca3a0e

https://github.com/anandnet/Harmony-Music/assets/127825700/8e835115-86e2-4153-8aa3-eba9971ef032

**Comment by anandnet** [comment]
@dainvincible1 i'm aware of this issue. This is happening because some stream url return 403 error. This issue has been fixed from package side so tomorrow i'll release a patch version.

**Comment by dainvincible1** [comment]
> @dainvincible1 i'm aware of this issue. This is happening because some stream url return 403 error. This issue has been fixed from package side so tomorrow i'll release a patch version.

thank you very much. btw, great app

**Comment by anandnet** [comment]
@dainvincible1 please check v1.3.2 if issue has resolved then we are good to close this.

**Comment by dainvincible1** [comment]
> @dainvincible1 please check v1.3.2 if issue has resolved then we are good to close this.

yes, its working. thank you
