### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by riorom73** [anandnet/Harmony-Music#355]
**Is your feature request related to a problem or new idea? Please describe.**
I feel frustrated when I want to leave my phone on for an hour only listening to songs during the night, but I can't do it because it's not right to leave the phone all night on.

**Describe the solution you'd like**
Insert the TIMER function.

**Comment by VedantJadhav701** [comment]
Like a sleep timer its a big problem while sleeping

**Comment by anandnet** [comment]
Already available, check https://github.com/anandnet/Harmony-Music/issues/240#issuecomment-2191043764
