### ISSUE TITLE
Not able to import all songs from playlist

### ISSUE THREAD

**Issue by dainvincible1** [anandnet/Harmony-Music#37]
https://github.com/anandnet/Harmony-Music/assets/127825700/77967a1d-d67b-47b0-915c-aad2ba67b713

I tried to import a playlist from youtube music with 300 songs but only 100 songs were imported to harmony music

**Comment by anandnet** [comment]
if appropriate, can you please share the url of this playlist? and in case you observe this issue in small size plalist please let me know that would be easier in troubleshooting.

**Comment by dainvincible1** [comment]
> if appropriate, can you please share the url of this playlist? and in case you observe this issue in small size playlist please let me know that would be easier in troubleshooting.

@anandnet this is the url of the playlist 
https://music.youtube.com/playlist?list=PLSh0rzVipQKstEmjrroBwgX4HEeEWq-7t&feature=share
and no, this issue is not there in small size playlist

**Comment by anandnet** [comment]
Fixed in v1.4.0

**Comment by Joni8829** [comment]
> Fixed in v1.4.0

Well, it's back again?

**Comment by Kaladin-tormentas** [comment]
The error is back again. :(

**Comment by Kaladin-tormentas** [comment]
> The error is back again. :(

Ohh fixed on v1.11.2  : )
