### ISSUE TITLE
Music is getting stopped suddenly

### ISSUE THREAD

**Issue by ItsMeTryCodING** [anandnet/Harmony-Music#375]
**Describe the bug**
Music is getting stopped suddenly even though having good network .
Have to click on pause and play buttons to play music

**Smartphone (please complete the following information):**
 - Device:  Moto edge 50 pro
 - OS: Android 14

**Additional context**

**Comment by Shubham315417** [comment]
In my phone also song are stop automatically from background  
         Device : vivo t2x 5g 
          OS. : 14

**Comment by anandnet** [comment]
You can try by enabling "ignore battery optimization" from settings->Music & Playback section.

**Comment by jbarasa** [comment]
Same problem here even with ignore optimization enabled. Device OS android 13

**Comment by anandnet** [comment]
Fixed now, please check new version.
