### ISSUE TITLE
Bottom Navigation Bar Moved to the bottom after restoring backup

### ISSUE THREAD

**Issue by blacklizzt** [anandnet/Harmony-Music#380]
**Describe the bug**
i use bottom nav on android, when i backup all my playlist (no downloaded file) to my linux (debian), the navigation setting is also brought to desktop version. It kinda affect the playback UI because its overlaid on top of it. But still functional. It's an issue when the app is on fullscreen (like 1st screenshot) but not on smaller window.
 
**To Reproduce**
1. Set the navigation to bottom in Android version
2. Make Backup App data
3. Restore it in Desktop version

**Expected behavior**
The navigation should be stick to the left or atleast not included in App Backup process
Or the setting for bottom navigation should be also an option for desktop version

**Screenshots**
![Screenshot from 2024-12-09 15-11-57](https://github.com/user-attachments/assets/b28dac65-33c1-46be-81e3-5e728ad00d40)
![Screenshot from 2024-12-09 15-21-25](https://github.com/user-attachments/assets/afcbe371-8c3e-45d6-a40b-c2957bc1713d)

**Smartphone (please complete the following information):**
 - Galaxy A54 5G
 - OS: Android 14 with One UI 6.1
 - Laptop: Thinkpad X270  i5 Gen6 with Debian 12 Gnome

**Comment by anandnet** [comment]
Hi @blacklizzt , please check https://github.com/anandnet/Harmony-Music/issues/378#issuecomment-2533568712
