### ISSUE TITLE
The song can't play duo a server restricction

### ISSUE THREAD

**Issue by MinSecurity09** [anandnet/Harmony-Music#381]
The song can't play in android and pc, for some reason, the message is: "The song can't play duo server restriction", when the 10 version come I have the problem, Solutions please

**Comment by MinSecurity09** [comment]
No

**Comment by MinSecurity09** [comment]
I'm not using a VPN

**Comment by anandnet** [comment]
If it not happening for all songs then song must be related to harmful content, it will be fixed in next release,   if it is happening for all songs sometimes you can turn on and off flight mode or you can reboot your router, so that your public ip changed and soft ban will be removed.

**Comment by anandnet** [comment]
Fixed now, please check new version.
