### ISSUE TITLE
Music continues playing after closing the application

### ISSUE THREAD

**Issue by jvgom** [anandnet/Harmony-Music#386]
**Describe the bug**
When I close the application the music continues playing, and if I start the app again, it does not start correctly. Nothing is seen in the application.
If I pause the song before closing the application and then start it again, it starts correctly

**Expected behavior**
When I close the app, the music should stop.
When you start the application again it should start correctly.

**Screenshots**
![Captura desde 2024-12-17 18-42-49](https://github.com/user-attachments/assets/13f80a73-036c-4420-b05b-5d13470e70bd)
![Captura desde 2024-12-17 18-43-14](https://github.com/user-attachments/assets/9764271a-0b40-49d5-8495-8bab2e0feb64)

**Smartphone (please complete the following information):**
 - Device: Desktop
 - OS: Debian 12

**Additional context**

**Comment by anandnet** [comment]
Go to settings->music and playback section and disable background playing.
