### ISSUE TITLE
Empty Playlist name

### ISSUE THREAD

**Issue by ketan2jangid** [anandnet/Harmony-Music#387]
**Describe the bug**
User is able to create playlist with no name, i.e. user can create playlist with name being just spaces (" "), which I guess is a bug

**To Reproduce**
1. Go to 'Playlist' tab
2. Click on '+' 
3. Just enter spaces for the name
4. Hit 'Create'. A new playlist with no name is created
5. The same can be done while renaming a playlist or creating new playlist from youtube playlist

**Expected behavior**
User should not be allowed to create playlist with no name. A toast should be displayed stating the same.

**Screenshots**

![Screenshot_20241218_133850](https://github.com/user-attachments/assets/0686922d-1889-4cfd-8b48-11a34cd147c0)
![Screenshot_20241218_134124](https://github.com/user-attachments/assets/9dccfe46-06de-48fc-81a3-e751d3cf762d)

**Smartphone (please complete the following information):**
 - Device: [Moto G62 5G]
 - OS: [e.g. Android 13]

In screenshots - Pixel 3a running on Android 9 (emulator)

**Additional context**
Can be fixed by just changing the condition for check before creating new playlist and renaming a playlist.

**Comment by anandnet** [comment]
Thanks for PR, merged.

**Comment by ketan2jangid** [comment]
Glad I could help. Hope I can contribute more once I understand the codebase completely :)
BTW thanks for this amazing app.
