### ISSUE TITLE
Can't play a song

### ISSUE THREAD

**Issue by VillainJambi** [anandnet/Harmony-Music#389]
I can only play one song, after that everything stops, I can't play other songs anymore

**Comment by anandnet** [comment]
Any specific error?

**Comment by VillainJambi** [comment]
No. I have to log back in to play another song. If I change the song, it just stops. The song time shows 0:00-0:00

**Comment by VillainJambi** [comment]
No. I have to log back in to play another song. If I change the song, it just stops. The song time shows 0:00-0:00

**Comment by sotha1** [comment]
same problem on my android here

**Comment by anandnet** [comment]
Fixed now, please check new version.
