### ISSUE TITLE
App Not working 

### ISSUE THREAD

**Issue by AseesMehtabAli1234** [anandnet/Harmony-Music#392]
**Describe the bug*
Everything is working except music player, whatever music you play it just keeps on loading and on trying to download it shows network error, API is not working

**Comment by mkr-infinity** [comment]
same problem i request the dev to update it.
also newpipe account not loging server error.

**Comment by anandnet** [comment]
yeah, seems yt is returning 403 error for streams with ip blocking.  you can try by turning on and off flight mode or rebooting your router, this will reset your public ip.

**Comment by anandnet** [comment]
Fixed now, please check new version.

**Comment by mkr-infinity** [comment]
> Fixed now, please check new version.

still same issue
now no songs playing
may be the API error.

**Comment by anandnet** [comment]
> > Fixed now, please check new version.
> 
> still same issue
> now no songs playing
> may be the API error.

Please check this.
https://github.com/anandnet/Harmony-Music/issues/396#issuecomment-2585374776
