### ISSUE TITLE
Selective Download

### ISSUE THREAD

**Issue by tengkuizdihar** [anandnet/Harmony-Music#40]
**Is your feature request related to a problem or new idea? Please describe.**
Add download feature for a playlist or per song.

**Describe the solution you'd like**
Theres already a cache system at play, maybe we can utilize that.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by siggi1984** [comment]
> **Is your feature request related to a problem or new idea? Please describe.** Add download feature for a playlist or per song.
> 
> **Describe the solution you'd like** Theres already a cache system at play, maybe we can utilize that.
> 
> **Describe alternatives you've considered** None
> 
> **Additional context** None

Would be a great addition to the APP.

**Comment by spl3g** [comment]
Yeah, selective download would be great. But maybe anandnet thinks about it the same way as the author of the Vimusic app, he doesn't want people to think that his app is a music downloader.

**Comment by anandnet** [comment]
Added in v1.6.0
