### ISSUE TITLE
Sometimes the song skips few seconds or maybe it gets faster. Im not able to understand what happens exactly 

### ISSUE THREAD

**Issue by dainvincible1** [anandnet/Harmony-Music#46]
https://github.com/anandnet/Harmony-Music/assets/127825700/0b84ace6-cd64-4dbd-a976-c7832c7dc86b

https://github.com/anandnet/Harmony-Music/assets/127825700/45de4fdc-aad8-4824-854b-e06a1a285a94

https://github.com/anandnet/Harmony-Music/assets/127825700/64782e15-1534-4269-9aed-b0eadea8c432

https://github.com/anandnet/Harmony-Music/assets/127825700/38b73d0e-0b72-4bcf-88f8-c068dbefcd31

**Comment by anandnet** [comment]
@dainvincible1 this is because you have enabled skip Silence. Please disable this from settings and try.

**Comment by dainvincible1** [comment]
> @dainvincible1 this is because you have enabled skip Silence. Please disable this from settings and try.

ahh damn got it, thank you so much it worked

**Comment by dainvincible1** [comment]
> @dainvincible1 this is because you have enabled skip Silence. Please disable this from settings and try.

ahh damn got it, thank you so much it worked
