### ISSUE TITLE
loop song does not work

### ISSUE THREAD

**Issue by github-user93** [anandnet/Harmony-Music#49]
**Describe the bug**
clicking on the loop button does not loop the song, the song just stops after reaching the end.

**To Reproduce**
1. play a song
2. try to loop it by clicking on the loop playback button
3. does not loop

**Expected behavior**
the song should loop

**Screenshots**
https://youtu.be/NgzGnxA_MdQ

**Smartphone (please complete the following information):**
 - Device: Redmi note 7 pro
 - OS: Android 10, miui 12.5.1

**Additional context**
no

**Comment by dainvincible1** [comment]
https://github.com/anandnet/Harmony-Music/assets/127825700/ce8341dd-b6ff-45c6-a464-1094a9bfc84f

my loop works

**Comment by anandnet** [comment]
@github-user93 you are right, loop is not working properly,i will look at it

**Comment by anandnet** [comment]
@github-user93 fixed in v1.5.0, you may check
