### ISSUE TITLE
When i search "lady gaga", the "result" and "video" section is blank

### ISSUE THREAD

**Issue by dainvincible1** [anandnet/Harmony-Music#53]
I tried with different mobiles but even in those the "result" and "video" section is blank for "lady gaga". Among the few other artists i searched only lady gaga is having this issue 

https://github.com/anandnet/Harmony-Music/assets/127825700/6d8ac3f9-9020-4576-9299-085a1563acd4

**Comment by anandnet** [comment]
Seems there is some exception caught in videos section. Will look and fix it
