### ISSUE TITLE
Showing wrong lyrics

### ISSUE THREAD

**Issue by dainvincible1** [anandnet/Harmony-Music#55]
![image](https://github.com/anandnet/Harmony-Music/assets/127825700/bbeb940d-b374-4c4a-8749-a4bffc0e9581)
![image](https://github.com/anandnet/Harmony-Music/assets/127825700/971fb1d6-def8-4ec8-bef1-dbad31d96842)

**Comment by anandnet** [comment]
@dainvincible1 can't do anything in this case bro :laughing: , because it is showing what youtube music api is returning, you may check Ytmusic as well , you will see same thing happening there.
