### ISSUE TITLE
Can't Create Playlists Successfully

### ISSUE THREAD

**Issue by HonestAbe7** [anandnet/Harmony-Music#56]
I tried to create a playlist by adding the song I wanted and then to create a playlist. Unfortunately, it said it was created but looking at the playlists, nothing is there. I even went to the Playlist section and tried to create one and still wasn't successful. Please fix this. Thanks

**Comment by anandnet** [comment]
@HonestAbe7  i don't know how this is happening, could you please share screen recording so that i can reproduce this issue.

**Comment by anandnet** [comment]
closing as no response from you. if you are still facing this issue you can reopen this thread.
