### ISSUE TITLE
If possible, please make the content names of Home, Songs, playlists, albums, artists look brighter 

### ISSUE THREAD

**Issue by dainvincible1** [anandnet/Harmony-Music#61]
![image](https://github.com/anandnet/Harmony-Music/assets/127825700/743cf786-e521-4045-8011-73fa2c2ab3a0)
In the songs section please make the song name and artist name look brighter
![image](https://github.com/anandnet/Harmony-Music/assets/127825700/15625b6c-1e8f-48ca-8612-f40ebe265228)
In the playlist section please make the name of the playlist look brighter
![image](https://github.com/anandnet/Harmony-Music/assets/127825700/ee7bcc78-f81d-4be0-bad7-55ec9239009b)
In album section please make the album name look brighter

**Comment by anandnet** [comment]
Check v1.5.0
