### ISSUE TITLE
TYPO - Euqalizer

### ISSUE THREAD

**Issue by SlayVPA** [anandnet/Harmony-Music#62]
typo under "Equalizer" description in settings menu

In the "settings" the "Equalizer" option the description has a typo:

EQUALIZER
- open system 'euqalizer' 

Just giving little help for this great project you're developing. Loving the project!!!

**Screenshots**
![Screenshot_20230926-125831.png](https://github.com/anandnet/Harmony-Music/assets/14207905/34e0ba6d-e668-4fd7-a473-a37c3f30731b)

 - Device: Pixel 7a
 - OS: Android 14 beta UPB5.230623.009

**Comment by anandnet** [comment]
Thanks for pointing out! Fixed in v1.5.0
