### ISSUE TITLE
Song save & sync lyrics

### ISSUE THREAD

**Issue by KrisTamang** [anandnet/Harmony-Music#65]
It is possible to make songs as data but not caches...
Cause it erase songs slower...and please make possible to back songs just like playlist..I wanna replace my music player with this...
And please when sync lyrics doesn't found switch it automatically into normal lyrics..!!
Hope it is possible

**Comment by anandnet** [comment]
Saving song is now possible from v1.6.0. Closing this thread as #66 has already been opened for sync lyrics.
