### ISSUE TITLE
language

### ISSUE THREAD

**Issue by senolfndk** [anandnet/Harmony-Music#67]
Can you add Turkish language?

**Comment by senolfndk** [comment]
> > Türkçe dili ekleyebilir misiniz?
> 
> Bu isteği 19.07.2023 tarihinde zaten göndermiştiniz.
> 
> #21
> 
> Çifte gönderilen isteklerin geliştiricinin değerli zamanına mal olduğunu ve dolayısıyla APP'nin geliştirilmesini geciktirdiğini düşünüyorum.

I'm sorry sir, I'm sorry

**Comment by anandnet** [comment]
@senolfndk  if you wish, you can help us in Turkish translation https://hosted.weblate.org/projects/harmony-music/#languages

**Comment by senolfndk** [comment]
> @senolfndk Dilerseniz Türkçe çeviri konusunda bize yardımcı olabilirsiniz https://hosted.weblate.org/projects/harmony-music/#languages

I'm not an expert on this subject
