### ISSUE TITLE
Songs can not be deleted from the cached/offline

### ISSUE THREAD

**Issue by siggi1984** [anandnet/Harmony-Music#68]
See screen rec.

https://github.com/anandnet/Harmony-Music/assets/103368536/972206b6-cf99-4671-9bb6-ce2983880f5e

**Comment by anandnet** [comment]
Thanks, i also observed that. will look into it.
Workaround -> you can also remove cache songs from here Library Playlist -> Cached/Offline playlist

**Comment by siggi1984** [comment]
> Thanks, i also observed that. will look into it. Workaround -> you can also remove cache songs from here Library Playlist -> Cached/Offline playlis

This way does not remove the songs either.

**Comment by anandnet** [comment]
@siggi1984 Fixed in v1.6.0 , you may check now.
