### ISSUE TITLE
added link to artist page 

### ISSUE THREAD

**Issue by siggi1984** [anandnet/Harmony-Music#69]
Clicking on the artist's name in the song player below the title should take you to the artist's page. Without the current detours.

Would such a function be possible.

![272187500-9fc63e06-4580-4d65-b4ba-ee5d891f0fda](https://github.com/anandnet/Harmony-Music/assets/103368536/e7f8c845-91c8-4f0b-b339-039e7e6774af)

**Comment by anandnet** [comment]
@siggi1984 i can add this but this will not work if any song contains more than one artist. So, better just give a long press on album art image, bottom sheet will show you all the artist of current song and then you can go to artist page from there.
