### ISSUE TITLE
 when searching cant add artist to favorites

### ISSUE THREAD

**Issue by zipolo123** [anandnet/Harmony-Music#74]
![Screenshot_20231011-210954_Harmony_Music](https://github.com/anandnet/Harmony-Music/assets/142728847/cf80d766-0834-404a-a4bc-27180226370f)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung s20]
 - OS: [e.g. Android 10]

**Additional context**

**Comment by zipolo123** [comment]
Button "Artists" disapear :(

**Comment by anandnet** [comment]
Could you please show us screen recording of the issue for better understanding?

**Comment by zipolo123** [comment]
Hello,
  
The bookmark "Artist" disappeared when I try for example search for an artist, then when I want to add na artist to favourites there is a bookmark "community playlists".    Theo issue appear when I add 3 artists to favorites and I cant add more.
  

  

  

Begin forwarded message:

**Comment by zipolo123** [comment]
Hello,
The bookmark "Artist" disappeared when I try for example search for an artist, then when I want to add na artist to favourites there is a bookmark "community playlists".  Theo issue appear when I add 3 artists to favorites and I cant add more.
![Uploading Screenshot_20231015-083758_Harmony_Music~2.png…]()

**Comment by anandnet** [comment]
Sorry for delay in response. Tab is dynamicaly populated on the basis of search data return from Ytube music so, we can't do anything to fix this rather than you can try with changing query string and perform search (like replace "ę" with "e" in "Wagę").
