### ISSUE TITLE
Poweramp equalizer not working 

### ISSUE THREAD

**Issue by max5354** [anandnet/Harmony-Music#82]
Poweramp equalizer is not working with harmony music app even i already turned on "equalizer" option of harmony music. I already restart my phone but still poweramp equalizer not detecting harmony music. Plz fix this.

Device : Samsung galaxy j8
Android 10

**Comment by anandnet** [comment]
@max5354 Currently Harmony music supports only device inbuilt equalizer.

**Comment by max5354** [comment]
But it will be great if you implement poweramp equalizer support in next beta/release.

**Comment by jaum20** [comment]
Please add support to poweramp eq
