### ISSUE TITLE
View Album, View Artist etc on Song Select From Playlist

### ISSUE THREAD

**Issue by anxiouslelimo** [anandnet/Harmony-Music#91]
**Is your feature request related to a problem or new idea? Please describe.**
An option to show the View Album and View Artist of a song from Playlist

**Describe the solution you'd like**
While long pressing on a song in playlist an option to show the View Album and View Artist menu option

**Additional context**
This would be greatly helpful for navigation within the app

**Comment by anandnet** [comment]
Already impleted but you can't view these in Piped playlist because data return from piped is very limited. i have mentioned here as well(https://github.com/anandnet/Harmony-Music/wiki/Piped-linking#limitation-of-piped-playlist). So, closing this for now.
