### ISSUE TITLE
Optional Horizontal Tab Layout

### ISSUE THREAD

**Issue by anxiouslelimo** [anandnet/Harmony-Music#95]
**Is your feature request related to a problem or new idea? Please describe.**
Currently we have vertical tab layout. A horizontal tab layout will be space efficient for some phone models and easier for older people to use the app.

**Describe the solution you'd like**
An optional horizontal tab layout settings.

**Describe alternatives you've considered**
On opening the app user can choose the layout.

This is one of the best apps i have found out. Kudos to the makers.

**Comment by anandnet** [comment]
Bottom navigation bar added in v1.8.0.
