### ISSUE TITLE
Lockscreen's album art appears in very low quality

### ISSUE THREAD

**Issue by max5354** [anandnet/Harmony-Music#96]
![Screenshot_20231206-203207_1DM](https://github.com/anandnet/Harmony-Music/assets/90886938/b843692b-bc8b-42c8-8c98-2d19ded99136)

Device : Samsung galaxy j8
Cpu architecture: v7a
Android 10

**Comment by anandnet** [comment]
@max5354 check now in v1.7.0.

**Comment by max5354** [comment]
> @max5354 check now in v1.7.0.

Thanks bro for solving this bug
